### PR TITLE
Feature/style

### PR DESCRIPTION
**Pull request by benmarten**
Mostly styling changes, modernizing.
Fixing all warnings, lint errors, except JSDOC and public visibility in Leanplum.js

Open Todos:
- Before merging we still need to fix the unit tests again, something broke during refactoring...
- Also web push is likely broken, due to heavy refactoring...

Please have an initial look at this one ;)

### CODE REVIEW

**Comment by alexisoyama** [comment]
Last commit fixes the unit tests. I'm going to try to run a sample now.

**Comment by alexisoyama** [comment]
Is this ready to review/merge?

**Comment by MaitreyaBuddha** [comment]
Did a preliminary check using the Sample. It had exceptions registering and unregistering for push.

**Comment by alexisoyama** [comment]
Commits are in https://github.com/Leanplum/Leanplum-JavaScript-SDK/pull/11

**Pull request closed without merging**
